#!/usr/bin/env bash
#SBATCH -p hebbe 
#SBATCH -A C3SE2021-1-15 # Project
#SBATCH -J test # Name of the job
#SBATCH -N 2 # Use 1 node
#SBATCH -n 30 # Use only 1 core on that node
#SBATCH -t 10:00:01 # Maximum time
#SBATCH -o stdout # stdout goes to this file
#SBATCH -e stderr # stderr goes to this file
module purge
#module load Python/3.7.4 Tkinter/3.7.4 intel/2019a ASE GPAW
#module load iccifort/2019.5.281 impi/2018.5.288
#module load GPAW/20.1.0-Python-3.7.4
#module load ASE/3.19.0-Python-3.7.4
module load  GCC/8.3.0 OpenMPI/3.1.4 GPAW/20.10.0-ASE-3.20.1-Python-3.7.4


mpirun python T5_2.py -k 500 


echo "runing completed at" $(date +"%I:%M:%S") >> Done.txt
