#!/usr/bin/env bash
#SBATCH -p hebbe 
#SBATCH -A C3SE2021-1-15 # Project
#SBATCH -J test # Name of the job
#SBATCH -N 2 # Use 1 node
#SBATCH -n 20 # Use only 1 core on that node
#SBATCH -t 12:00:01 # Maximum time
#SBATCH -o stdout # stdout goes to this file
#SBATCH -e stderr # stderr goes to this file
module purge
module load Python/3.7.4 Tkinter/3.7.4 intel/2019a ASE GPAW

mpirun gpaw-python RDFO.py 


echo "runing completed at" $(date +"%I:%M:%S") >> Done.txt
