#!/usr/bin/env bash
#SBATCH -p hebbe 
#SBATCH -A C3SE2021-1-15 # Project
#SBATCH -J task1 # Name of the job
#SBATCH -N 1 # Use 1 node
#SBATCH -n 1 # Use only 1 core on that node
#SBATCH -t 05:00:00 # Maximum time
#SBATCH -o stdout # stdout goes to this file
#SBATCH -e stderr # stderr goes to this file
#module purge
#module load Python/3.7.4 Tkinter/3.7.4 intel/2019a ASE GPAW

#echo "The Cluster computer seems to work"
#sleep 60

#python initialization.py 6
#python initialization.py 7
#python initialization.py 8

python ga.py

